### ISSUE TITLE
Doesn't work on node 0.9

### ISSUE THREAD

**Issue by isaacs** [TooTallNate/node-weak#14]
This may well be a node issue, but it looks like you're touching a V8 property that has moved or changed.

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Object27GetPointerFromInternalFieldEi
  Referenced from: /Users/isaacs/dev/js/lru-cache/node_modules/weak/build/Release/weakref.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v86Object27GetPointerFromInternalFieldEi
  Referenced from: /Users/isaacs/dev/js/lru-cache/node_modules/weak/build/Release/weakref.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
```
